SBS/app/urls.py
from django.contrib.auth.views import LogoutView
from django.http import HttpResponse
from django.urls import re_path

from app.views.HomeViews import HomeView, DashboardView
from app.views.Logging.LoggingViews import SystemLogsView, TransactionLogsView, SystemLogsDate, TransactionLogsDate
from app.views.PKI.PKIViews import PkiView, EncryptView, DecryptView, GenerateRSA, UserPublicKeyAPI
from app.views.PiiViews import PiiView, GovtPIIAccess, ViewPii
from app.views.TestViews import TestErrors
from app.views.accounts.AccountViews import UserAccountsView, AccountView, UsersHavingAccountView, \
    UserAddAccountView
from app.views.known_accounts.KnownAccountsViews import EnterKnownAccountsView, ViewKnownAccounts
from app.views.login.LoginViews import MyLoginView
from app.views.payment_accounts.PaymentAccountViews import EnterPaymentAccountsView, ViewPaymentccounts, \
    RemovePaymentAccounts
from app.views.signup.SignUpViews import SignUp, OTPImage, UserConfirmation, \
    PasswordResetConfirm, PasswordResetRequestView
from app.views.JavaScriptDisableViews import JavaScriptDisableView

from app.views.su.SuViews import CustomSuLogout, CustomSuLogin, CustomSuLoginAsUser
from app.views.transactions.TransactionViews import TransactionRequest, TransactionView, \
    TransactionPending, TransactionCompleted, TransactionLocator, TransactionRisky
from app.views.users.UserViews import AllUsersView, UserProfile, UserRequestsReceivedView, \
    UserRequestView, UserProfileEdit, UserDelete

app_name = 'app'

urlpatterns = [
    re_path(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),

    re_path(r'^$', HomeView.as_view(), name='HomeView'),
    re_path(r'^login/$', MyLoginView.as_view(), name='MyLoginView'),
    re_path(r'^logout/$', LogoutView.as_view(), name='LogoutView'),

    re_path(r'^api/superuser/generate-rsa/$', GenerateRSA.as_view(), name='GenerateRSA'),

    re_path(r'^pki/$', PkiView.as_view(), name='PkiView'),
    re_path(r'^api/pki/$', UserPublicKeyAPI.as_view(), name='UserPublicKeyAPI'),
    # re_path(r'^encrypt/$', EncryptView.as_view(), name='EncryptView'),
    # re_path(r'^decrypt/$', DecryptView.as_view(), name='DecryptView'),

    # re_path(r'^change-password/$', ChangePassword.as_view(), name='ChangePassword'),
    re_path(r'^password-reset-initiate/$', PasswordResetRequestView.as_view(), name='PasswordResetRequestView'),
    re_path(r'^password-reset-confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',PasswordResetConfirm.as_view(), name='confirm_password_reset'),

    re_path(r'^signup/$', SignUp.as_view(), name='SignUp'),
    re_path(r'^otp-image/$', OTPImage.as_view(), name='OTPImage'),
    re_path(r'^dashboard/$', DashboardView.as_view(), name='DashboardView'),
  
    re_path(r'^jserror/',JavaScriptDisableView.as_view(), name="JavaScriptDisable"),

    re_path(r'^user/all/$', AllUsersView.as_view(), name='AllUsersView'),
    re_path(r'^user/(?P<user_id>[0-9]+)/$', UserProfile.as_view(), name='UserProfile'),
    re_path(r'^user/(?P<user_id>[0-9]+)/edit/$', UserProfileEdit.as_view(), name='UserProfileEdit'),
    re_path(r'^user/delete/$', UserDelete.as_view(), name='UserDelete'),

    re_path(r'^user/pii/$',ViewPii.as_view(), name='ViewPii'),
    re_path(r'^pii/(?P<user_id>[0-9]+)/$', PiiView.as_view(), name='Pii'),
    re_path(r'^pii/(?P<uidb1>[0-9A-Za-z_\-]+)/(?P<uidb2>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', GovtPIIAccess.as_view(), name='GovtPIIAccess'),

    re_path(r'^enter-known-account/$', EnterKnownAccountsView.as_view(), name='enter_known_account'),
    re_path(r'^view-known-account/$', ViewKnownAccounts.as_view(), name='view_known_account'),
    re_path(r'^enter-payment-account/$', EnterPaymentAccountsView.as_view(), name='enter_payment_account'),
    re_path(r'^view-payment-account/$', ViewPaymentccounts.as_view(), name='view_payment_account'),
    re_path(r'^remove-payment-account/$', RemovePaymentAccounts.as_view(), name='remove_payment_account' ),

    re_path(r'^user/request/$', UserRequestsReceivedView.as_view(), name='UserRequestsReceivedView'),
    re_path(r'^user/request/(?P<user_request_id>[0-9]+)/$', UserRequestView.as_view(), name='UserRequestView'),

    re_path(r'^account/(?P<user_id>[0-9]+)/add/$', UserAddAccountView.as_view(), name='UserAddAccountView'),
    re_path(r'^account/(?P<user_id>[0-9]+)/all/$', UserAccountsView.as_view(), name='UserAccountsView'),
    re_path(r'^account/(?P<user_id>[0-9]+)/(?P<account_id>[0-9]+)/$', AccountView.as_view(), name='AccountView'),
    re_path(r'^account/all/$', UsersHavingAccountView.as_view(), name='UsersHavingAccountView'),

    re_path(r'^transaction/risky/$', TransactionRisky.as_view(), name='TransactionRisky'),
    re_path(r'^transaction/pending/$', TransactionPending.as_view(), name='TransactionPending'),
    re_path(r'^transaction/completed/$', TransactionCompleted.as_view(), name='TransactionCompleted'),
    re_path(r'^transaction/create/$', TransactionRequest.as_view(), name='TransactionRequest'),
    re_path(r'^transaction/(?P<transaction_id>[0-9]+)/$', TransactionView.as_view(), name='TransactionView'),
    re_path(r'^transaction/locator/$', TransactionLocator.as_view(), name='TransactionLocator'),

    re_path(r'^confirm-account/(?P<uidb>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', UserConfirmation.as_view(), name='UserConfirmation'),

    re_path(r'^system-logs-files/$', SystemLogsView.as_view(), name='SystemLogsView'),
    re_path(r'^system-logs/(?P<log_id>[0-9]+)/$', SystemLogsDate.as_view(), name='SystemLogsDate'),
    re_path(r'^transaction-logs-files/$', TransactionLogsView.as_view(), name='TransactionLogsView'),
    re_path(r'^transaction-logs/(?P<log_id>[0-9]+)/$', TransactionLogsDate.as_view(), name='TransactionLogsDate'),

    # Switch User
    re_path(r'^switch-user/$', CustomSuLogout.as_view(), name='CustomSuLogout'),
    re_path(r'^switch-user/login/$', CustomSuLogin.as_view(), name='CustomSuLogin'),
    re_path(r'^switch-user/(?P<user_id>[0-9]+)/$', CustomSuLoginAsUser.as_view(), name='CustomSuLoginAsUser'),

    # Test Errors
    re_path(r'^test-errors/$', TestErrors.as_view(), name='TestErrors'),

    # Include built-in pages for authentication
    # re_path(r'^', include('django.contrib.auth.urls')),
]

SBS/bank/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    # TODO: Change to custom page
    # path('admin/', admin.site.urls),

    path('admin/is/the/new/superuser/', admin.site.urls),

    re_path(r'^', include('app.urls')),

    # Session-Security Urls
    re_path(r'^session_security/', include('session_security.urls')),

    # Django-Su Urls
    re_path(r'^switch-user/', include('django_su.urls')),
]

SBS/app/forms/PKIForms.py
from django import forms

from app.models import PublicKey


class PKIForms(forms.ModelForm):

    class Meta:
        model = PublicKey
        fields = ('publickey',)
        labels = {
            'publickey': "Public Key"
        }

SBS/app/forms/TransactionForms.py
from django import forms
from django.core.exceptions import ValidationError
from django_filters import FilterSet, NumberFilter, ModelChoiceFilter

from app.forms.LoginForms import MyAuthenticationForm
from app.models import Transaction, Account, MyUser


class ExternalRequestForm(forms.ModelForm):
    pki_token = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Transaction
        fields = ('from_account', 'to_account', 'amount', 'approved_by', 'complete_time', 'pki_token')
        labels = {
            'complete_time': 'Completed at'
        }

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(*args, **kwargs)

        self.fields['to_account'].required = False
        self.fields['from_account'].required = False

        if self.user.is_individual_user():
            self.fields['from_account'].queryset = Account.objects.filter(user=self.user, user__is_active=True)
            to_accounts = Account.objects.filter(known_account__user=self.user, user__is_active=True).exclude(user__username=MyUser.ANON) | Account.objects.filter(user=self.user, user__is_active=True).exclude(user__username=MyUser.ANON)
            self.fields['to_account'].queryset = to_accounts.distinct()

        if self.user.is_merchant():
            self.fields['from_account'].queryset = Account.objects.filter(user=self.user, user__is_active=True) | Account.objects.filter(payment_account__merchant_user=self.user, user__is_active=True).exclude(user__username=MyUser.ANON)
            to_accounts = Account.objects.filter(known_account__user=self.user, user__is_active=True).exclude(user__username=MyUser.ANON) | Account.objects.filter(user=self.user, user__is_active=True).exclude(user__username=MyUser.ANON) | Account.objects.filter(payment_account__merchant_user=self.user, user__is_active=True).exclude(user__username=MyUser.ANON)
            self.fields['to_account'].queryset = to_accounts.distinct()

        instance = getattr(self, 'instance', None)
        if instance and instance.id:
            self.fields['from_account'].queryset = Account.objects.all().exclude(user__username=MyUser.ANON, user__is_active=True).exclude(user__is_staff=True)

            if instance.is_complete:
                pass
            else:
                self.fields.pop('approved_by')
                self.fields.pop('complete_time')
        else:
            self.fields.pop('approved_by')
            self.fields.pop('complete_time')

    def clean(self):
        cleaned_data = super().clean()

        from_account = cleaned_data['from_account']
        to_account = cleaned_data['to_account']

        if not (from_account or to_account):
            raise ValidationError('Both From and To can not be empty.', code='empty from to')

        if from_account == to_account:
            raise ValidationError('Both From and To can not be same', code='same from to')

        if to_account and self.user != to_account.user and from_account is None and not self.user.is_internal_user():
            raise ValidationError('Cannot credit to someone else account')

        if from_account and self.user != from_account.user and self.user.is_individual_user():
            raise ValidationError('Cannot transfer from someone else account')

        return cleaned_data

    def clean_amount(self):
        amount = self.cleaned_data['amount']
        from_account = self.cleaned_data['from_account']

        if amount < 0:
            raise ValidationError('Negative Amount', code='negative amount')

        if amount == 0:
            raise ValidationError('Zero Amount', code='zero amount')

        if from_account and from_account.balance < amount:
            raise ValidationError('Low Balance', code='low balance')

        return amount


class InternalRequestForm(ExternalRequestForm):

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super().__init__(user, *args, **kwargs)

        self.fields['from_account'].queryset = Account.objects.all().exclude(user__username=MyUser.ANON, user__is_active=True).exclude(user__is_staff=True)
        self.fields['to_account'].queryset = Account.objects.all().exclude(user__username=MyUser.ANON, user__is_active=True).exclude(user__is_staff=True)


class VerifyOTPForm(MyAuthenticationForm):

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)

        self.fields.pop('username')
        self.fields.pop('password')

    def get_user(self):
        user = self.request.user

        return user


def filter_account_based_on_user_from(request):
    if request is None:
        return Account.objects.none()

    user = request.user

    if user.is_internal_user():
        return Account.objects.all().exclude(user__username=MyUser.ANON).exclude(user__is_staff=True)

    elif user.is_individual_user():
        return Account.objects.filter(user=user).exclude(user__username=MyUser.ANON).exclude(user__is_staff=True)

    elif user.is_merchant():
        return Account.objects.filter(payment_account__merchant_user=user).exclude(user__username=MyUser.ANON).exclude(user__is_staff=True) | Account.objects.filter(user=user).exclude(user__username=MyUser.ANON).exclude(user__is_staff=True)

    else:
        return Account.objects.none()


def filter_account_based_on_user_to(request):
    if request is None:
        return Account.objects.none()

    user = request.user

    if user.is_internal_user():
        return Account.objects.all().exclude(user__username=MyUser.ANON).exclude(user__is_staff=True)

    elif user.is_individual_user():
        return (Account.objects.filter(user=user).exclude(user__username=MyUser.ANON).exclude(user__is_staff=True) | Account.objects.filter(known_account__user=user).exclude(user__username=MyUser.ANON).exclude(user__is_staff=True)).distinct()

    elif user.is_merchant():
        return (Account.objects.filter(payment_account__merchant_user=user).exclude(user__username=MyUser.ANON).exclude(user__is_staff=True) | Account.objects.filter(user=user).exclude(user__username=MyUser.ANON).exclude(user__is_staff=True) | Account.objects.filter(known_account__user=user).exclude(user__username=MyUser.ANON).exclude(user__is_staff=True)).distinct()

    else:
        return Account.objects.none()


def get_transaction_queryset(user):
    queryset = Transaction.objects.none()

    if user.is_internal_user():
        queryset = Transaction.objects.filter(is_approved=True) | Transaction.objects.filter(is_approved=False, from_account__user__is_active=True) | Transaction.objects.filter(is_approved=False, to_account__user__is_active=True)

    elif user.is_individual_user():
        queryset = Transaction.objects.filter(from_account__user=user) | Transaction.objects.filter(to_account__user=user)
        queryset = queryset.filter(is_approved=True) | queryset.filter(is_approved=False, from_acount__user__is_active=True) | queryset.filter(is_approved=False, to_account__user__is_active=True)

    elif user.is_merchant():
        queryset = Transaction.objects.filter(from_account__user=user) | Transaction.objects.filter(to_account__user=user) | Transaction.objects.filter(to_account__payment_account__merchant_user=user) | Transaction.objects.filter(from_account__payment_account__merchant_user=user)
        queryset = queryset.filter(is_approved=True) | queryset.filter(is_approved=False, from_acount__user__is_active=True) | queryset.filter(is_approved=False, to_account__user__is_active=True) | queryset.filter(is_approved=False, from_account__payment_account__merchant_user__is_active=True) | queryset.filter(is_approved=False, to_account__payment_account__merchant_user__is_active=True)

    return queryset.distinct()


class TransactionLocatorForm(FilterSet):
    amount__gt = NumberFilter(field_name='amount', lookup_expr='gt')
    amount__lte = NumberFilter(field_name='amount', lookup_expr='lte')

    from_account = ModelChoiceFilter(queryset=filter_account_based_on_user_from)
    to_account = ModelChoiceFilter(queryset=filter_account_based_on_user_to)

    class Meta:
        model = Transaction
        fields = ('id', 'from_account', 'to_account', 'amount__gt', 'amount__lte', 'is_complete')

SBS/app/views/HomeViews.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.base import View
from app.mixins import LoginAndOTPRequiredMixin
from app.views import CommonHelpers


class HomeView(View):

    def get(self, request):

        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('app:DashboardView'))

        return render(request, 'home.html', {
            'home': True,
        })


class DashboardView(LoginAndOTPRequiredMixin, View):

    def get(self, request):

        user = request.user

        links = []
        balance = None

        if user.is_admin():
            template = 'dashboard.html'
            title = 'Admin'
            links = CommonHelpers.get_admin_links()
        elif user.is_manager():
            template = 'dashboard.html'
            title = 'Manager'
            links = CommonHelpers.get_manager_links()
        elif user.is_employee():
            template = 'dashboard.html'
            title = 'Employee'
            links = CommonHelpers.get_employee_links()
        elif user.is_merchant():
            template = 'dashboard.html'
            title = 'Merchant'
            links = CommonHelpers.get_merchant_links(user.id)
            balance = CommonHelpers.get_user_total_balance(user.id)
        elif user.is_individual_user():
            template = 'dashboard.html'
            title = 'Individual User'
            links = CommonHelpers.get_individual_user_links(user.id)
            balance = CommonHelpers.get_user_total_balance(user.id)
        else:
            template = 'error.html'
            title = ''

        return render(request, template, {
            'title': title,
            'links': links,
            'balance': balance,
        })

SBS/app/templates/JSDisable.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    {% include 'common_head.html' %}
    <title>SBS</title>
</head>
<body>
{% include 'navbar.html' %}

	<div class="d-flex flex-column align-items-center mt-4">
		<h1>Error</h1>
		<p>{{ err }}</p>
	</div>
</body>
</html>

SBS/app/templates/create_pki.html
{% extends 'home.html' %}

{% block content %}

	<h1>{{ title }}</h1>

{% endblock %}

{% block body_scripts %}
	{% include 'pki.html' with redirect=True %}
	<script>
		generateKeys();
	</script>
{% endblock %}

SBS/app/templates/encryptdata.html
<script>

	function getEncryptedData(data) {
		toEncrypt('{{ publickey }}', data)
			.catch(function () {
				console.log('Could not encrypt message');
			});
	}

	function convertStringToArrayBufferView(str){
	    var bytes = new Uint8Array(str.length);
	    for (var iii = 0; iii < str.length; iii++){
	        bytes[iii] = str.charCodeAt(iii);
	    }
	    return bytes;
	}


    async function toEncrypt(pubkey, data) {

		pubkey = window.atob(pubkey);

		let publickey = convertStringToArrayBufferView(pubkey);
        publickey = await MakePublicKey(publickey);
        let convert_data = convertStringToArrayBufferView(data);
        let encrypteddata = await encrypt(convert_data, publickey);
        let edata = btoa(String.fromCharCode.apply(null, new Uint8Array(encrypteddata)));

        addTokenToForm(edata);
    }

    function MakePublicKey(pubkey) {

        return window.crypto.subtle.importKey(
            "spki",
            pubkey,
            {
                name: "RSA-OAEP",
                hash: {name: "SHA-256"},
            },
            false,
            ["encrypt"]
        )
    }


    function encrypt(data, keys) {

        return window.crypto.subtle.encrypt(
            {
                name: "RSA-OAEP",
            },
            keys,
            data
        )
    }

</script>

SBS/app/templates/error.html
{% extends 'base.html' %}

{% block body %}
	{% include 'navbar.html' %}

	<div class="d-flex flex-column align-items-center mt-4">
		<h1>Error</h1>
		<p>{{ err }}</p>
	</div>
{% endblock %}

SBS/app/templates/filter_template.html
{% extends 'form_template.html' %}

{% block after_form %}

	<div class="mt-5">
		{% for transaction in filter.qs %}
			<div class="h5">
				<a href="{% url 'app:TransactionView' transaction.id %}">
					{{ transaction }}
				</a>
			</div>
		{% endfor %}
	</div>

{% endblock %}

SBS/app/templates/form_template.html
{% extends 'dashboard.html' %}

{% block head %}
	{% if extra_form_virtual_keyboard or form_virtual_keyboard %}
		{% include 'virtualkeyboardscripts.html' %}
	{% endif %}
{% endblock %}

{% block content %}

	<h2>{{ title }}</h2>

	<form {% if get %} method="{{ get }}" {% else %} method="post" {% endif %} id="form_id" class="mt-5 d-flex flex-column w-100 align-items-center">

		{% if not get %}
			{% csrf_token %}
		{% endif %}

		{% include 'form.html' with form=form showVirtualKeyboard=form_virtual_keyboard %}

		{% if extra_form %}
			<hr class="w-50">

			{% if not extra_form_readonly %}

				{% include 'form.html' with form=extra_form showVirtualKeyboard=extra_form_virtual_keyboard readonly=False %}

			{% else %}

				{% include 'form.html' with form=extra_form showVirtualKeyboard=extra_form_virtual_keyboard %}

			{% endif %}
		{% endif %}

		<hr class="w-50">

		{% if hide_btn and link %}
			<div class="d-flex w-100 justify-content-center py-1">
				<a class="btn btn-dark mx-2" href="{{ link.1 }}">
					{{ link.0 }}
				</a>
			</div>
		{% endif %}

		{% if not hide_btn %}
			<div class="d-flex w-100 justify-content-center py-1">

				{% if link %}
					<a class="btn btn-dark mx-2" href="{{ link.1 }}">
						{{ link.0 }}
					</a>
				{% endif %}

				{% if extra_btn2_title %}
					<input type="submit" class="btn btn-dark mx-2"
					       value="{{ extra_btn2_title }}" name="{{ extra_btn2_title }}"
					>
				{% endif %}

				<input type="submit" class="btn btn-dark mx-2"
				{% if btn_title %}
					value="{{ btn_title }}"
					name="{{ btn_title }}"
				{% endif %}
				>

				{% if extra_btn_title %}
					<input type="submit" class="btn btn-dark mx-2"
					       value="{{ extra_btn_title }}" name="{{ extra_btn_title }}"
					>
				{% endif %}

				<input id="submit-id" type="hidden" />
			</div>
		{% endif %}

	</form>

	{% block after_form %}{% endblock %}

{% endblock %}

{% block body_scripts %}

	{% if use_pki %}
		<script>
			function addTokenToForm(token) {
				$('#id_pki_token').val(token);
			}
		</script>

		{% include 'encryptdata.html' with publickey=use_pki.public_key %}
		{% include 'getprivatekeyanddecrpt.html' with edata=use_pki.edata %}

		<script>
			getDecryptedData();
		</script>
	{% endif %}

	<script>
		$(':submit').click(function (event) {
			$(':submit').attr('disabled', true);

			let button = event.target;
			$('#submit-id').attr('name', button.value).val(button.value);

			$('#form_id').submit();
		});
	</script>

{% endblock %}

SBS/app/templates/mail.html
<p>Welcome To SBS</p>
<p>
	Below is a one-time activation link.
	After your email is confirmed, you will be shown a highly sensitive QR Code that will help you set up Google Authenticator for you. Be sure not to share it with anyone.
	This is a required set up. Without this, you will not be able to sign in to your account.
</p>

{% if DEBUG %}
	<a href="http://127.0.0.1:8000{% url 'app:UserConfirmation' uidb token %}">
		http://127.0.0.1:8000{% url 'app:UserConfirmation' uidb token %}
	</a>
{% else %}
	<a href="https://192.168.2.235:443{% url 'app:UserConfirmation' uidb token %}">
		https://192.168.2.235:443{% url 'app:UserConfirmation' uidb token %}
	</a>
{% endif %}

SBS/app/templates/mail_passwordreset.html
<p>Welcome To SBS</p>
<p>
	Below is a one-time activation link.
	After your email is confirmed, you will be shown a link where you can set up a password for your account.
    Be sure not to share it with anyone. This is a required set up. Without this, you will not be able to sign in to your account.
</p>

{% if DEBUG %}
	<a href="http://127.0.0.1:8000{% url 'app:confirm_password_reset' uidb64 token %}">
		http://127.0.0.1:8000{% url 'app:confirm_password_reset' uidb64 token %}
	</a>
{% else %}
	<a href="https://192.168.2.235:443{% url 'app:confirm_password_reset' uidb64 token %}">
		https://192.168.2.235:443{% url 'app:confirm_password_reset' uidb64 token %}
	</a>
{% endif %}

SBS/app/templates/pii_access_mail.html
<p>
	You have received a request from {{ from_user }} to view PII details of {{ target_user }}.
</p>

{% if DEBUG %}
	<a href="http://127.0.0.1:8000{% url 'app:GovtPIIAccess' uidb1 uidb2 token %}">
		http://127.0.0.1:8000{% url 'app:GovtPIIAccess' uidb1 uidb2 token %}
	</a>
{% else %}
	<a href="https://192.168.2.235:443{% url 'app:GovtPIIAccess' uidb1 uidb2 token %}">
		https://192.168.2.235:443{% url 'app:GovtPIIAccess' uidb1 uidb2 token %}
	</a>
{% endif %}

SBS/app/templates/pki.html
{% csrf_token %}

{% if not hideDiv %}
	<div class="d-flex flex-column align-items-center mt-5">
		<p id="div"></p>
	</div>
{% endif %}

<script>

	function generateKeys() {
		encryptDataSaveKey().catch(function () {
			console.log('Could not create RSA key pair');
		});
	}

    async function encryptDataSaveKey() {

	    let keys = await makeKeys();

	    let public_keys = keys.publicKey;
	    let pub_key_object = await crypto.subtle.exportKey("spki", public_keys);
	    let pk = btoa(String.fromCharCode.apply(null, new Uint8Array(pub_key_object)));

	    let private_keys = keys.privateKey;

	    let priv_key_object = await crypto.subtle.exportKey("jwk", private_keys);

	    let final_priv_key =await window.crypto.subtle.importKey(
	        "jwk",
	        {
	            kty: "RSA",
	            e: "AQAB",
	            dp: priv_key_object.dp,
	            dq: priv_key_object.dq,
	            d: priv_key_object.d,
	            n: priv_key_object.n,
	            p: priv_key_object.p,
	            q: priv_key_object.q,
	            qi: priv_key_object.qi,
	            alg: "RSA-OAEP-256",
	            ext: true,
	        },
	        {
	            name: "RSA-OAEP",
	            hash: {name: "SHA-256"},
	        },
	        false,
	        ["decrypt"]
	    );



	    callOnStore(function (store) {
	        store.put({user:'{{ user }}', keys: final_priv_key});
	    });

	    let post= await $.ajax({
			type:"POST",
			url:"{% url 'app:UserPublicKeyAPI' %}",
			data: {
			    'publickey': pk,
			     csrfmiddlewaretoken: '{{ csrf_token }}'
			},
		    success: function () {
			    {% if redirect %}
				    document.getElementById('div').innerText = 'Keys Generated';

				    setTimeout(function () {
					    window.location = '/';
				    }, 1000);
			    {% endif %}
		    }
	    });

    }

    function callOnStore(fn_) {

        var indexedDB = window.indexedDB || window.mozIndexedDB || window.webkitIndexedDB || window.msIndexedDB || window.shimIndexedDB;

        var open = indexedDB.open("SBS", 1);

        open.onupgradeneeded = function() {
            var db = open.result;
            var store = db.createObjectStore("Key", {keyPath: "user"});
            store.createIndex("key_sbs","keys", {unique: true});
        };

        open.onsuccess = function() {
            // Start a new transaction
            var db = open.result;
            var tx = db.transaction("Key", "readwrite");
            var store = tx.objectStore("Key");

            fn_(store);

            tx.oncomplete = function() {
                db.close();
            };
        }
    }

    function makeKeys() {
        return window.crypto.subtle.generateKey(
        {
            name: "RSA-OAEP",
            modulusLength: 1024,
            publicExponent: new Uint8Array([0x01, 0x00, 0x01]),
            hash: {name: "SHA-256"},
        },

        true,
        ["encrypt", "decrypt"]
       )
    }

</script>